server:
  port: 8080

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Klapsa2503/actuator-test
          default-label: master
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
